# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEvento', models.DateField()),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=256)),
                ('Congregacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membros.Congregacao')),
            ],
        ),
        migrations.CreateModel(
            name='EventoDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEvento', models.DateField()),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=256)),
                ('Congregacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membros.Congregacao')),
            ],
        ),
        migrations.CreateModel(
            name='EventoGeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEvento', models.DateField()),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=256)),
                ('Congregacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membros.Congregacao')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEventoCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarioChegada', models.TimeField()),
                ('EventoCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.EventoCargo')),
                ('Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membros.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEventoDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarioChegada', models.TimeField()),
                ('EventoDepartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.EventoDepartamento')),
                ('Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membros.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEventoGeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarioChegada', models.TimeField()),
                ('EventoGeral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.EventoGeral')),
                ('Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membros.Pessoa')),
            ],
        ),
    ]
