# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=156)),
                ('Congregacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membros.Congregacao')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.Departamento')),
                ('Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membros.Pessoa')),
            ],
        ),
    ]
